apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: benchflow-collect-metrics
  labels:
    app.kubernetes.io/name: benchflow
spec:
  templates:
    - name: collect-metrics
      inputs:
        parameters:
          - name: BENCHFLOW_IMAGE
          - name: RUN_PLAN
          - name: BENCHMARK_START_TIME
          - name: BENCHMARK_END_TIME
          - name: EXECUTION_NAME
      script:
        image: "{{inputs.parameters.BENCHFLOW_IMAGE}}"
        command:
          - bash
        source: |
          set +e
          bflow metrics collect \
            --run-plan-json '{{inputs.parameters.RUN_PLAN}}' \
            --benchmark-start-time '{{inputs.parameters.BENCHMARK_START_TIME}}' \
            --benchmark-end-time '{{inputs.parameters.BENCHMARK_END_TIME}}' \
            --artifacts-dir '/workspace/results/{{inputs.parameters.EXECUTION_NAME}}'
          rc=$?
          if [ "$rc" -eq 0 ]; then
            echo Succeeded > /workspace/workflow-state/metrics-status.txt
          else
            echo Failed > /workspace/workflow-state/metrics-status.txt
          fi
          exit 0
        volumeMounts:
          - name: results
            mountPath: /workspace/results
          - name: workflow-state
            mountPath: /workspace/workflow-state
