apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: benchflow-wait-for-endpoint
  labels:
    app.kubernetes.io/name: benchflow
spec:
  templates:
    - name: wait-for-endpoint
      inputs:
        parameters:
          - name: BENCHFLOW_IMAGE
          - name: RUN_PLAN
      container:
        image: "{{inputs.parameters.BENCHFLOW_IMAGE}}"
        command:
          - bflow
        args:
          - wait
          - endpoint
          - --run-plan-json
          - "{{inputs.parameters.RUN_PLAN}}"
